CREATE TABLE USERS (
    ID                   NUMBER  NOT NULL,
    NAME                VARCHAR2(32) NOT NULL,
    IS_ADMIN             NUMBER(1,0) NOT NULL,
    EMAIL               VARCHAR2(32) NOT NULL,
    PASSWORD            VARCHAR2(32) NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY ( ID )
);

CREATE TABLE PRESENTATIONS (
    ID                   NUMBER  NOT NULL,
    PRESENTER_ID         NUMBER NOT NULL,
    TITLE                VARCHAR2(32) NOT NULL,
    SUMMARY              VARCHAR2(64),
    IS_APPROVED           NUMBER(0,1) NOT NULL,
    CONSTRAINT PK_PRESENTATIONS PRIMARY KEY ( ID )
);

CREATE TABLE SESSIONS (
    ID                   NUMBER  NOT NULL,
    PRESENTATION_ID      NUMBER NOT NULL,
    ROOM                VARCHAR2(32) NOT NULL,
    TIME              VARCHAR2(64) NOT NULL,
    CONSTRAINT PK_SESSIONS PRIMARY KEY ( ID )
);

ALTER TABLE PRESENTATIONS ADD CONSTRAINT FK_PRESENTER_ID FOREIGN KEY ( PRESENTER_ID ) REFERENCES PRESENTERS( ID ) ON DELETE CASCADE;
ALTER TABLE SESSIONS ADD CONSTRAINT FK_PRESENTATION_ID FOREIGN KEY ( PRESENTATION_ID ) REFERENCES PRESENTATIONS( ID ) ON DELETE CASCADE;

INSERT INTO USERS (ID, NAME, IS_ADMIN, EMAIL, PASSWORD) VALUES (1, "Steph", true, "steph@company.com", "fake-password");
INSERT INTO USERS (ID, NAME, IS_ADMIN, EMAIL, PASSWORD) VALUES (2, "Shawn", false, "shawn@company.com", "fake-password2");
INSERT INTO PRESENTATION (ID, PRESENTER_ID, TITLE, SUMMARY, IS_APPROVED) VALUES (1, 2, "Debugging with a Mobile Perspective", "Attend this presentation to learn how to debug mobile apps.", false);
INSERT INTO SESSIONS (ID, PRESENTATION_ID, ROOM, TIME) VALUES (1, 1, "Bucktown", "Bucktown");